In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Features: [study_hours, attendance_percent, sleep_hours]
X = np.array([
    [1.0, 55, 5.0],
    [2.0, 60, 5.5],
    [2.5, 62, 6.0],
    [3.0, 65, 5.0],
    [3.5, 70, 6.5],
    [4.0, 72, 6.0],
    [4.5, 75, 6.5],
    [5.0, 78, 7.0],
    [5.5, 80, 6.5],
    [6.0, 82, 7.0],
    [6.5, 85, 7.5],
    [7.0, 88, 8.0]
], dtype=float)

# Target: 0 = fail, 1 = pass
y = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=float)

m, n = X.shape

print("X shape:",X.shape)
print("y shape:",y.shape)
print("m =", m, ", n =", n)



X shape: (12, 3)
y shape: (12,)
m = 12 , n = 3


In [3]:
def standardize_features(X):
    mu = X.mean(axis=0)
    sigma = X.std(axis=0)
    sigma[sigma==0] = 1.0
    X_scaled = (X - mu) / sigma

    return X_scaled, mu, sigma

def apply_standardization(X, mu, sigma):
    return (X - mu) / sigma

X_scaled, mu, sigma = standardize_features(X)

print("\nFeature means:", mu)
print("Feature std:", sigma)
print("Scaled X:\n", X_scaled)



Feature means: [ 4.20833333 72.66666667  6.375     ]
Feature std: [ 1.79650509 10.06092552  0.89267855]
Scaled X:
 [[-1.78587489 -1.75596834 -1.54030809]
 [-1.22923856 -1.25899617 -0.98019606]
 [-0.95092039 -1.0602073  -0.42008403]
 [-0.67260223 -0.762024   -1.54030809]
 [-0.39428407 -0.26505182  0.14002801]
 [-0.1159659  -0.06626296 -0.42008403]
 [ 0.16235226  0.23192035  0.14002801]
 [ 0.44067043  0.53010365  0.70014004]
 [ 0.71898859  0.72889252  0.14002801]
 [ 0.99730676  0.92768139  0.70014004]
 [ 1.27562492  1.22586469  1.26025208]
 [ 1.55394308  1.52404799  1.82036411]]


In [1]:
def sigmoid(z):
    return 1 / 1 + np.exp(-z)

In [2]:
def predict_probability(x, w, b):
    z = np.dot(w, x) + b
    return sigmoid(z)